server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false
  jackson:
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.security: WARN

jwt:
  secret: ${JWT_SECRET:mi_clave_super_secreta_ultra_segura_de_256_bits_minimo_1234567890}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:86400000}
